%define INSTANCE /home/zope

instancehome $INSTANCE

%import ZEO

# debug-mode on

<zodb_db main>
    # Main FileStorage database
    <clientstorage>
        server $INSTANCE/var/zeosocket
        storage main
        name zeostorage Data.fs
        client-label zms6_alpine
    </clientstorage>
    mount-point /
</zodb_db>


# <zodb_db main>
#    <filestorage>
#      path $INSTANCE/var/Data.fs
#    </filestorage>
#    mount-point /
# </zodb_db>


# Uncomment this if you use Products.Sessions and Products.TemporaryFolder
<zodb_db temporary>
    <temporarystorage>
      name Temporary database (for sessions)
    </temporarystorage>
    mount-point /temp_folder
    container-class Products.TemporaryFolder.TemporaryContainer
</zodb_db>

<environment>
  CHAMELEON_CACHE $INSTANCE/var/cache
</environment>
