version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: zms5_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zms5_dosis
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/18/data
