FROM ubuntu:24.04

# Install Zope/ZEO Dependencies
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN update-ca-certificates
RUN apt-get install -y make gcc g++ git build-essential
RUN apt-get install -y python3 python3-dev python3-venv
RUN apt-get install -y default-libmysqlclient-dev build-essential pkg-config
RUN apt-get install -y slapd libldap2-dev libsasl2-dev
RUN apt-get install -y memcached

RUN adduser --disabled-password zope && usermod -aG sudo zope
USER zope
WORKDIR /home/zope/
ENV VIRTUAL_ENV=/home/zope/venv

RUN python3 -m venv venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install -U pip wheel setuptools
RUN pip install -U -e git+https://github.com/zms-publishing/ZMS.git#egg=ZMS
RUN pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/master/requirements-full.txt
RUN pip install ZEO
RUN pip install itsdangerous
RUN pip install debugpy

# Create Zope Instance
RUN mkwsgiinstance -d venv/instance/zms5 -u admin:admin

COPY ./etc venv/instance/zms5/etc
COPY ./var venv/instance/zms5/var
COPY ./Extensions venv/instance/zms5/Extensions

EXPOSE 8085
EXPOSE 8086
EXPOSE 8080
EXPOSE 5678

# Finally Start ZEO/Zope by Script
# ENTRYPOINT ["/bin/sh -c"]
CMD ["/home/zope/venv/instance/zms5/etc/start.sh"]