FROM ubuntu:24.04

# Install OS Requirements
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN update-ca-certificates
RUN apt-get -y upgrade
RUN apt-get install -y locales locales-all
RUN apt-get install -y make gcc g++ git build-essential
RUN apt-get install -y python3 python3-dev python3-venv
RUN apt-get install -y default-libmysqlclient-dev build-essential pkg-config
RUN apt-get install -y slapd libldap2-dev libsasl2-dev
RUN apt-get install -y memcached

RUN adduser --disabled-password zope && usermod -aG sudo zope
USER zope
WORKDIR /home/zope/

ENV VIRTUAL_ENV=/home/zope/venv
ENV SHELL=/bin/bash
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

RUN python3 -m venv venv
RUN pip install -U pip wheel setuptools
RUN pip install -U -e git+https://github.com/zms-publishing/ZMS.git@main#egg=ZMS
RUN pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/master/requirements-full.txt
RUN pip install ZEO
RUN pip install itsdangerous
# RUN pip install debugpy

# Create Zope Instance
RUN mkwsgiinstance -d . -u admin:admin

COPY ./etc etc
COPY ./var var
COPY ./Extensions Extensions

EXPOSE 5678
EXPOSE 8080
EXPOSE 8086
EXPOSE 8085

# Finally Start ZEO/Zope by Script
# ENTRYPOINT ["/bin/sh -c"]
CMD ["/home/zope/etc/start.sh"]