# Zope configuration variables
%define INSTANCE_HOME /home/zope
%define VIRTUAL_ENV /home/zope/venv


instancehome $INSTANCE_HOME
ip-address 0.0.0.0
debug-mode on

<zodb_db main>
   <filestorage>
     path $INSTANCE_HOME/var/Data.fs
   </filestorage>
   mount-point /
</zodb_db>


<zodb_db temporary>
	# Temporary storage database (for sessions)
	<temporarystorage>
		name temporary storage for sessioning
	</temporarystorage>
	mount-point /temp_folder
	container-class Products.TemporaryFolder.TemporaryContainer
</zodb_db>

<environment>
  CHAMELEON_CACHE $INSTANCE_HOME/var/cache
</environment>
