import test_util
import test_zreferableitem
import test_zmscontainerobject
import test_zmslinkelement
import test_multilang
import test_performance
import test_pilutil
import test_standard
import test_xmllib
