version: "3.7"
services:
  zope-relstorage:
    build: .
    image: zope:relstorage
    ports:
      - 5432:5432
      - 8080:8080
    environment:
      - PYTHONUNBUFFERED="1"
      - CONFIG_FILE="/home/zope/etc/zope.ini"
      - INSTANCE_HOME="/home/zope"
      - CLIENT_HOME="/home/zope"
      - PYTHON="/home/zope/venv/bin/python"
      - SOFTWARE_HOME="/home/zope/venv/bin"
    # volumes:
    #   - ./etc/:/home/zope/etc/
    #   - ./Extensions/:/home/zope/Extensions/:rw
    #   - ./var/:/home/zope/var/:rw

    # command: /home/zope/etc/start.sh
