version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_15
    environment:
      - POSTGRES_USER=zodb
      - POSTGRES_PASSWORD=zodb
      - POSTGRES_DB=zodb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/conf/pg_hba.conf:/var/lib/postgresql/conf/pg_hba.conf
    command: postgres -D /var/lib/postgresql/data -c hba_file=/var/lib/postgresql/conf/pg_hba.conf
    networks:
      - zms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zodb"]
      interval: 5s
      timeout: 5s
      retries: 10

  zms5:
    image: zms5:relstorage 
    build:
      context: .
      dockerfile: dockerfile
    container_name: zms5_relstorage
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/home/zope/etc/zope.ini
      - INSTANCE_HOME=/home/zope
      - CLIENT_HOME=/home/zope
      - RELSTORAGE_DSN=dbname=zodb user=zodb password=zodb host=postgres port=5432
      # Use for OpenSearch communication: http://opensearch-node:9200
      - OPENSEARCH_HOST=opensearch-node
      - OPENSEARCH_PORT=9200
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zms_network
    volumes:
      - ./Extensions/:/zope/home/Extensions/:z
      - ./var/:/home/zope/var/:z
      - ./etc/:/home/zope/etc/:z

# IMPORTANT: Create the Network first to make it external
# >docker network create zms_network
networks:
  zms_network:
    driver: bridge
    external: true