# Use a base image with Python
FROM python:3.11-slim

# Install OS Requirements
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y locales locales-all
RUN apt-get install -y make gcc g++ git build-essential curl
RUN apt-get install -y python3 python3-dev python3-venv
RUN apt-get install -y build-essential pkg-config
RUN apt-get install -y libpq-dev
RUN apt-get install -y memcached
RUN apt-get install -y postgresql-client


# Set environment variables
ENV VIRTUAL_ENV=/home/zope/venv
ENV SHELL=/bin/bash
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

# Add Zope User and Environment
RUN adduser --disabled-password zope && usermod -aG sudo zope
USER zope
WORKDIR /home/zope/

# Install Zope and RelStorage
RUN python3 -m venv venv
RUN pip install -U pip wheel setuptools
RUN pip install -r https://raw.githubusercontent.com/zopefoundation/Zope/master/requirements-full.txt
RUN pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/main/requirements.txt
RUN pip install git+https://github.com/zms-publishing/ZMS.git
RUN pip install RelStorage psycopg2-binary lxml 

# Create Zope Instance
RUN mkwsgiinstance -d . -u admin:admin

# Copy Zope configuration
COPY ./etc/zope.conf ./etc/zope.conf
COPY ./etc/zope.ini ./etc/zope.ini
COPY relstorage.code-workspace .

# Kopiere einen angepassten Entrypoint (ohne PostgreSQL-Start)
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
USER root
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose port for Zope
EXPOSE 8080

# Use the entrypoint script to start services
USER zope
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]