FROM python:3.10-alpine

EXPOSE 8080
EXPOSE 5678

RUN apk add python3 make gcc g++ git
RUN apk update && apk add mariadb-dev openldap-dev

# https://stackoverflow.com/questions/49955097/how-do-i-add-a-user-when-im-using-alpine-as-a-base-image 
RUN addgroup -S zope && adduser --disabled-password -S zope -G zope
USER zope
WORKDIR /home/zope/

RUN python3 -m venv venv
RUN venv/bin/pip install --upgrade pip wheel setuptools
RUN venv/bin/pip install https://github.com/zms-publishing/ZMS/archive/refs/heads/main.zip
RUN venv/bin/pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/master/requirements-full.txt
RUN venv/bin/pip install itsdangerous
RUN venv/bin/pip install debugpy

# Create Zope Instance
RUN venv/bin/mkwsgiinstance -d venv/instance/zms5 -u admin:admin
# Start Zope Server
CMD ["venv/bin/runwsgi", "--debug",  "--verbose", "venv/instance/zms5/etc/zope.ini", "debug-mode=on"]