FROM python:3.10-alpine

WORKDIR /home/zope/

RUN apk add python3 make gcc g++ git
RUN apk update && apk add mariadb-dev openldap-dev

RUN python3 -m venv venv
RUN venv/bin/pip install --upgrade pip wheel setuptools
RUN venv/bin/pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/master/requirements-full.txt
RUN venv/bin/pip install itsdangerous
RUN venv/bin/pip install debugpy

# Create Zope Instance
RUN venv/bin/mkwsgiinstance -d venv/instance/zms5 -u admin:admin
# Start Zope Server
CMD ["venv/bin/runwsgi", "--debug",  "--verbose", "venv/instance/zms5/etc/zope.ini", "debug-mode=on"]