version: "3.7"
services:
  zms5:
    build: .
    image: zms5:latest
    ports:
      - 8085:8085
      - 8086:8086
      - 8080:8080
      - 5678:5678
    environment:
      - PYTHONUNBUFFERED="1"
      - CONFIG_FILE="/home/zope/venv/instance/zms5/etc/zope.ini"
      - INSTANCE_HOME="/home/zope/venv/instance/zms5"
      - CLIENT_HOME="/home/zope/venv/instance/zms5"
      - PYTHON="/home/zope/venv/bin/python"
      - SOFTWARE_HOME="/home/zope/venv/bin"

    command:  /home/zope/venv/bin/runwsgi --debug --verbose /home/zope/venv/instance/zms5/etc/zope.ini debug-mode=on http_port=8086

    # volumes:
    #   - /home/zope/instance/zms5:/home/zope/instance/zms5
    #   - /home/zope/src/zms-publishing/ZMS5/:src