version: "3.7"
services:
  zms5-alpine:
    build: .
    image: zms5:alpine
    ports:
      - 5678:5678
      - 8080:8080
      - 8086:8086
      - 8085:8085
    environment: 
      - PYTHONUNBUFFERED="1"
      - CONFIG_FILE="/home/zope/etc/zope.ini"
      - INSTANCE_HOME="/home/zope"
      - CLIENT_HOME="/home/zope"
      - PYTHON="/home/zope/venv/bin/python"
      - SOFTWARE_HOME="/home/zope/venv/bin"
    volumes:
      - ./etc/:/home/zope/etc/
      - ./Extensions/:/home/zope/Extensions/:rw
      - ./var/:/home/zope/var/:rw

    # command: /home/zope/etc/start.sh
