FROM ubuntu:24.04

# Install OS Requirements
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN update-ca-certificates
RUN apt-get -y upgrade
RUN apt-get install -y locales locales-all
RUN apt-get install -y make gcc g++ git build-essential
RUN apt-get install -y python3 python3-dev python3-venv
RUN apt-get install -y default-libmysqlclient-dev build-essential pkg-config
RUN apt-get install -y slapd libldap2-dev libsasl2-dev
RUN apt-get install -y memcached

# Add Microsoft Package Servers for VSCode
RUN apt-get install -y curl apt-transport-https
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
RUN apt-get update
# Install VSCode Server as User root
RUN curl -fsSL https://code-server.dev/install.sh | sh

# Add Zope User and Environment
RUN adduser --disabled-password zope && usermod -aG sudo zope
USER zope
WORKDIR /home/zope/

ENV ZOPE_VERSION=6.0b2
ENV VIRTUAL_ENV=/home/zope/venv
ENV SHELL=/bin/bash
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

# Install ZMS and Zope in a Virtual Environment
RUN python3 -m venv venv
RUN pip install -U pip wheel setuptools
RUN pip install Zope[wsgi]==$ZOPE_VERSION -c https://zopefoundation.github.io/Zope/releases/$ZOPE_VERSION/constraints.txt
RUN pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/main/requirements-full.txt
# RUN pip install --use-pep517 --config-settings editable_mode=compat -e git+https://github.com/zms-publishing/ZMS.git@main#egg=ZMS
RUN pip install -e git+https://github.com/zms-publishing/ZMS.git@zms6a#egg=ZMS
RUN pip install ZEO
RUN pip install itsdangerous
# RUN pip install debugpy

# Create Zope Instance
RUN mkwsgiinstance -d . -u admin:admin

# Mount Zope Instance Data
COPY ./etc etc
COPY ./var var
COPY ./Extensions Extensions

# Expose Ports:
    # 8888 = Running VSCode-Server 
    # 8085 = Running Default Zope-Server on ZEO
    # 8086 = Provided for Debugger-Zope-Instance
EXPOSE 8888 
EXPOSE 8085
EXPOSE 8086

# Install VSCode Extension for local User zope
RUN code-server --install-extension ms-python.python --user-data-dir /home/zope/.local/share/code-server

# Finally apply shell-script as User zope for starting both
    # 1. VSCode-Server plus Python Extension 
    # 2. ZEO/Zope-Instance
CMD ["/home/zope/etc/start.sh"]
 