# Use a base image with Python
FROM python:3.11-slim

# Install OS Requirements
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y locales locales-all
RUN apt-get install -y make gcc g++ git build-essential curl
RUN apt-get install -y python3 python3-dev python3-venv
RUN apt-get install -y build-essential pkg-config
RUN apt-get install -y libpq-dev
RUN apt-get install -y memcached
RUN apt-get install -y postgresql-client

# Expose port for Zope
EXPOSE 8080

# Set environment variables
ENV VIRTUAL_ENV=/home/zope/venv
ENV SHELL=/bin/bash
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

# Add Zope User and Environment
RUN adduser --disabled-password zope && usermod -aG sudo zope
USER zope
WORKDIR /home/zope/

# Install Zope and RelStorage
RUN python3 -m venv venv
RUN pip install -U pip wheel setuptools
RUN pip install -r https://raw.githubusercontent.com/zms-publishing/ZMS5/main/requirements.txt
RUN pip install --use-pep517 --config-settings editable_mode=compat -e git+https://github.com/zms-publishing/ZMS.git@main#egg=ZMS
RUN pip install RelStorage psycopg2-binary lxml opensearch-py

# Create Zope Instance
RUN ./venv/bin/mkwsgiinstance -d . -u admin:admin

# Mount Zope Instance Data from Host
COPY --chown=zope:zope ./etc /home/zope/etc
COPY --chown=zope:zope ./var /home/zope/var
COPY --chown=zope:zope ./Extensions /home/zope/Extensions
COPY --chown=zope:zope ./relstorage.code-workspace /home/zope/relstorage.code-workspace
COPY --chown=+x. /entrypoint.sh /usr/local/bin/entrypoint.sh

# Use the entrypoint script to start services
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]