services:
  zms5-alpine:
    build: .
    image: zms5:alpine
    ports:
      - 8086:8086
      - 8085:8085
    networks:
      - zms_network
    environment: 
      - PYTHONUNBUFFERED="1"
      - CONFIG_FILE="/home/zope/etc/zope.ini"
      - INSTANCE_HOME="/home/zope"
      - CLIENT_HOME="/home/zope"
      - PYTHON="/home/zope/venv/bin/python"
      - SOFTWARE_HOME="/home/zope/venv/bin"
    volumes:
      - ./etc/:/home/zope/etc/
      - ./Extensions/:/home/zope/Extensions/:rw
      - ./var/:/home/zope/var/:rw

    ### Override the default CMD to launch script and keep container alive
    # command: sleep infinity
    command: >
      bash -c "
        /home/zope/etc/start.sh &
        sleep infinity
      "

# IMPORTANT: Create the Network first to make it external
# > docker network create zms_network
networks:
  zms_network:
    driver: bridge
